### ISSUE TITLE
测试了一下，控制器销毁后，不会立即释放网络请求

### ISSUE THREAD

**Issue by iWECon** [CoderMikeHe/WeChat#11]
控制器销毁后，如果存在未执行完的网络请求，还会继续执行。

**Comment by CoderMikeHe** [comment]
回调是异步的，所以会继续执行。一般好像都没有针对页面销毁，停掉网络请求的处理。当然前提是要保证 控制器要销毁，否侧会有问题。

**Comment by iWECon** [comment]
emmmm, 我想知道有没有办法手动把这个网络请求停掉, 我看 despose 里面有个 [task cancel]; 但是只有 task 执行完成了才会走, 等于没什么作用.

如果碰到网络较慢的情况的话, 连续走两遍刷新会刷出同样的数据. 或者说当一个页面有多个网络请求的时候, 无法停掉上一个请求会造成数据错乱.(当然有其他方法避免, 但是比较懒~)

**Comment by CoderMikeHe** [comment]
嗯嗯 平常大家好像都高度统一的忽略了退出界面取消网络请求了。[笑Cry]

**Comment by sushushu** [comment]
你们一般是直接拷贝代码进项目直接用吗？

**Comment by iWECon** [comment]
> 你们一般是直接拷贝代码进项目直接用吗？

我是照着搭一下，学习一下框架的结构设计

**Comment by CoderMikeHe** [comment]
一般会有个人搭建框架的，然后后面的小伙伴就可以直接用了，不用关注内部的实现。
