### ISSUE TITLE
朋友圈图片点击后无法显示

### ISSUE THREAD

**Issue by love865122909** [CoderMikeHe/WeChat#23]
朋友圈图片点击后无法显示

**Comment by CoderMikeHe** [comment]
是所有图片都不展示？

**Comment by love865122909** [comment]
是的呢

**Comment by CoderMikeHe** [comment]
通讯录列表的头像能展示？或者 你把朋友圈里面的图片链接放到网页上看能否展示？ 若还是不行  提供一下xcode 版本号

**Comment by love865122909** [comment]
通讯录列表 和朋友圈列表 图片都可以显示 只是点击朋友圈后的大图是无法显示的 我试试网页 下午看看

**Comment by love865122909** [comment]
只是模拟器不行 可能我的开发包有问题吧，真机是没有问题的 给楼主点个赞

**Comment by CoderMikeHe** [comment]
嗯，我也蛮久没看这块代码 我也慌！
