### ISSUE TITLE
在按照demo导入后，使用不了viewModel中的services

### ISSUE THREAD

**Issue by denglei022** [CoderMikeHe/WeChat#7]
自己新建了一个测试工程，把类都导入进来后报错，使用services中的方法self.viewModel.services dismissViewModelAnimated:YES  报错:method for selector 'popViewModelAnimated:'，很奇怪会出现这个问题，services中的client也使用不了，但是下载下来的Wechat demo是没有问题的，想知道是什么问题

**Comment by f2yu** [comment]
应该是引用的问题，只告诉了协议名字，没告诉编译器这个协议具体内容是什么
